/**
 * LemonSqueezy Product State Loader
 *
 * This file loads product URLs from the gitignored state file (.lemonsqueezy-products.json)
 * that is generated by scripts/create-lemonsqueezy-products.js
 *
 * The state file contains the actual checkout URLs for all 107 books × 2 payment options.
 */

interface ProductConfig {
  generatedAt: string;
  storeId: string;
  products: Array<{
    bookId: string;
    type: string;
    productId: string;
    variantId: string;
    checkoutUrl: string;
    productName: string;
  }>;
  productUrls: Record<string, string>;
}

// This will be populated from the state file
let productUrls: Record<string, string> = {};

/**
 * Load product URLs from state file
 *
 * In development, this reads from .lemonsqueezy-products.json
 * In production, you would load this from environment variables or a database
 */
export async function loadProductUrls(): Promise<Record<string, string>> {
  // If already loaded, return cached version
  if (Object.keys(productUrls).length > 0) {
    return productUrls;
  }

  try {
    // Try to load from state file (development)
    const response = await fetch('/.lemonsqueezy-products.json');

    if (response.ok) {
      const config: ProductConfig = await response.json();
      productUrls = config.productUrls;
      console.log(`✅ Loaded ${Object.keys(productUrls).length} product URLs from state file`);
      return productUrls;
    }
  } catch (error) {
    console.warn('⚠️ Could not load .lemonsqueezy-products.json - using fallback');
  }

  // Fallback: return empty object (will show "not configured" error)
  console.warn('⚠️ No LemonSqueezy products configured. Run: npm run lemonsqueezy:create');
  return {};
}

/**
 * Get product URL synchronously (use after loadProductUrls has been called)
 */
export function getProductUrl(productKey: string): string | undefined {
  return productUrls[productKey];
}

/**
 * Check if products are configured
 */
export function isConfigured(): boolean {
  return Object.keys(productUrls).length > 0;
}

/**
 * Get all product URLs (for debugging)
 */
export function getAllProductUrls(): Record<string, string> {
  return { ...productUrls };
}

// Auto-load on module import (in browser environment)
if (typeof window !== 'undefined') {
  loadProductUrls().catch((error) => {
    console.error('Failed to load LemonSqueezy products:', error);
  });
}

export default {
  loadProductUrls,
  getProductUrl,
  isConfigured,
  getAllProductUrls,
};
