import { createCheckout } from '@lemonsqueezy/lemonsqueezy.js';
import * as LemonSqueezyState from './lemonsqueezy-state';

/**
 * Product URLs are loaded from .lemonsqueezy-products.json (gitignored state file)
 * This file is generated by running: npm run lemonsqueezy:create
 *
 * To create products:
 * 1. Get your LemonSqueezy API key and Store ID
 * 2. Run: LEMONSQUEEZY_API_KEY=xxx LEMONSQUEEZY_STORE_ID=123 npm run lemonsqueezy:create
 * 3. The script will create all 214 products (107 books × 2 payment options)
 * 4. Product URLs will be saved to .lemonsqueezy-products.json
 */

export interface CheckoutOptions {
  productUrl: string;
  bookId?: string;
  bookTitle?: string;
  userEmail?: string;
}

export class LemonSqueezyService {
  /**
   * Open LemonSqueezy checkout (overlay mode)
   * Requires product URL from PRODUCT_URLS config
   */
  static openCheckout(options: CheckoutOptions): void {
    const { productUrl, bookId, userEmail } = options;

    // Add custom data to pass bookId through webhook
    const checkoutUrl = new URL(productUrl);
    if (bookId) {
      checkoutUrl.searchParams.set('checkout[custom][bookId]', bookId);
    }
    if (userEmail) {
      checkoutUrl.searchParams.set('checkout[email]', userEmail);
    }

    // Use overlay checkout for better UX
    createCheckout(checkoutUrl.toString(), {
      embed: false,
    });
  }

  /**
   * Direct redirect to checkout (fallback if overlay doesn't work)
   */
  static redirectToCheckout(options: CheckoutOptions): void {
    const { productUrl, bookId, userEmail } = options;

    const checkoutUrl = new URL(productUrl);
    if (bookId) {
      checkoutUrl.searchParams.set('checkout[custom][bookId]', bookId);
    }
    if (userEmail) {
      checkoutUrl.searchParams.set('checkout[email]', userEmail);
    }

    window.location.href = checkoutUrl.toString();
  }

  /**
   * Get product URL for a book (uses state file)
   */
  static getProductUrl(productKey: string): string | undefined {
    return LemonSqueezyState.getProductUrl(productKey);
  }

  /**
   * Check if LemonSqueezy is configured
   */
  static isConfigured(): boolean {
    const storeId = import.meta.env.VITE_LEMONSQUEEZY_STORE_ID;
    const hasProducts = LemonSqueezyState.isConfigured();
    return !!storeId && storeId !== 'your_store_id' && hasProducts;
  }

  /**
   * Load product URLs from state file (call this on app init)
   */
  static async loadProducts(): Promise<void> {
    await LemonSqueezyState.loadProductUrls();
  }
}
