/**
 * Stripe Product State Loader
 *
 * This file loads product/price IDs from the gitignored state file (.stripe-products.json)
 * that is generated by scripts/create-stripe-products.js
 *
 * The state file contains the actual price IDs for all 107 books × 2 payment options.
 */

interface PriceConfig {
  generatedAt: string;
  products: Array<{
    bookId: string;
    type: string;
    productId: string;
    priceId: string;
    productName: string;
  }>;
  priceIds: Record<string, string>;
}

// This will be populated from the state file
let priceIds: Record<string, string> = {};

/**
 * Load price IDs from state file
 *
 * In development, this reads from .stripe-products.json
 * In production, you would load this from environment variables or a database
 */
export async function loadPrices(): Promise<Record<string, string>> {
  // If already loaded, return cached version
  if (Object.keys(priceIds).length > 0) {
    return priceIds;
  }

  try {
    // Try to load from state file (development)
    const response = await fetch('/stripe-products.json');

    if (response.ok) {
      const config: PriceConfig = await response.json();
      priceIds = config.priceIds;
      console.log(`✅ Loaded ${Object.keys(priceIds).length} Stripe price IDs from state file`);
      return priceIds;
    }
  } catch (error) {
    console.warn('⚠️ Could not load .stripe-products.json - using fallback');
  }

  // Fallback: return empty object (will show "not configured" error)
  console.warn('⚠️ No Stripe products configured. Run: npm run stripe:create');
  return {};
}

/**
 * Get price ID synchronously (use after loadPrices has been called)
 */
export function getPriceId(productKey: string): string | undefined {
  return priceIds[productKey];
}

/**
 * Check if products are configured
 */
export function isConfigured(): boolean {
  return Object.keys(priceIds).length > 0;
}

/**
 * Get all price IDs (for debugging)
 */
export function getAllPriceIds(): Record<string, string> {
  return { ...priceIds };
}

// Auto-load on module import (in browser environment)
if (typeof window !== 'undefined') {
  loadPrices().catch((error) => {
    console.error('Failed to load Stripe products:', error);
  });
}

export default {
  loadPrices,
  getPriceId,
  isConfigured,
  getAllPriceIds,
};
