import * as StripeState from './stripe-state';

/**
 * Stripe Payment Service
 *
 * Product URLs are loaded from .stripe-products.json (gitignored state file)
 * This file is generated by running: npm run stripe:create
 *
 * To create products:
 * 1. Get your Stripe API key (Settings → Developers → API keys)
 * 2. Run: STRIPE_SECRET_KEY=sk_test_xxx npm run stripe:create
 * 3. The script will create all 214 products (107 books × 2 payment options)
 * 4. Product/Price IDs will be saved to .stripe-products.json
 */

export interface CheckoutOptions {
  priceId: string;
  bookId?: string;
  bookTitle?: string;
  userEmail?: string;
  userId?: string;  // Required for authentication
  isSubscription?: boolean;
}

export interface CollectionCheckoutOptions {
  priceId: string;
  userId: string;
  userEmail?: string;
  successUrl: string;
  cancelUrl: string;
  metadata: {
    type: string;
    collectionId: string;
    userId: string;
  };
}

// Stripe initialization (for future client-side use if needed)
// Currently using server-side checkout flow

export class StripeService {
  /**
   * Open Stripe Checkout
   * Requires price ID from PRODUCT_PRICES config
   */
  static async openCheckout(options: CheckoutOptions): Promise<void> {
    const { priceId, bookId, userEmail, userId, isSubscription = false } = options;

    if (!userId) {
      throw new Error('User must be signed in to make a purchase');
    }

    // Create checkout session via your backend
    const response = await fetch(`${import.meta.env.VITE_API_URL}/api/create-checkout-session`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        priceId,
        bookId,
        customerEmail: userEmail,
        userId,
        paymentType: isSubscription ? 'subscription' : 'lifetime',
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to create checkout session');
    }

    const { url } = await response.json();

    if (!url) {
      throw new Error('No checkout URL returned');
    }

    // Redirect to Stripe Checkout using standard redirect
    window.location.href = url;
  }

  /**
   * Create checkout session (for collections or custom flows)
   * Returns session object with URL for redirect
   */
  static async createCheckoutSession(options: CollectionCheckoutOptions): Promise<{ url: string }> {
    const { priceId, userId, userEmail, successUrl, cancelUrl, metadata } = options;

    if (!userId) {
      throw new Error('User must be signed in to make a purchase');
    }

    // Create checkout session via backend
    const response = await fetch(`${import.meta.env.VITE_API_URL}/api/create-checkout-session`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        priceId,
        userId,
        customerEmail: userEmail,
        successUrl,
        cancelUrl,
        metadata,
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to create checkout session');
    }

    const { url } = await response.json();

    if (!url) {
      throw new Error('No checkout URL returned');
    }

    return { url };
  }

  /**
   * Get price ID for a book (uses state file)
   */
  static getPriceId(productKey: string): string | undefined {
    return StripeState.getPriceId(productKey);
  }

  /**
   * Check if Stripe is configured
   */
  static isConfigured(): boolean {
    return StripeState.isConfigured();
  }

  /**
   * Load product prices from state file (call this on app init)
   */
  static async loadProducts(): Promise<void> {
    await StripeState.loadPrices();
  }
}
