import { loadStripe } from '@stripe/stripe-js';
import * as StripeState from './stripe-state';

/**
 * Stripe Payment Service
 *
 * Product URLs are loaded from .stripe-products.json (gitignored state file)
 * This file is generated by running: npm run stripe:create
 *
 * To create products:
 * 1. Get your Stripe API key (Settings → Developers → API keys)
 * 2. Run: STRIPE_SECRET_KEY=sk_test_xxx npm run stripe:create
 * 3. The script will create all 214 products (107 books × 2 payment options)
 * 4. Product/Price IDs will be saved to .stripe-products.json
 */

export interface CheckoutOptions {
  priceId: string;
  bookId?: string;
  bookTitle?: string;
  userEmail?: string;
  isSubscription?: boolean;
}

// Initialize Stripe.js
let stripePromise: ReturnType<typeof loadStripe> | null = null;

function getStripe() {
  if (!stripePromise) {
    const publishableKey = import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY;
    if (!publishableKey || publishableKey === 'your_publishable_key') {
      console.error('Stripe publishable key not configured');
      return null;
    }
    stripePromise = loadStripe(publishableKey);
  }
  return stripePromise;
}

export class StripeService {
  /**
   * Open Stripe Checkout
   * Requires price ID from PRODUCT_PRICES config
   */
  static async openCheckout(options: CheckoutOptions): Promise<void> {
    const { priceId, bookId, userEmail, isSubscription = false } = options;

    // Create checkout session via your backend
    const response = await fetch(`${import.meta.env.VITE_API_URL}/api/create-checkout-session`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        priceId,
        bookId,
        customerEmail: userEmail,
        isSubscription,
        successUrl: `${window.location.origin}/purchase-success?session_id={CHECKOUT_SESSION_ID}`,
        cancelUrl: `${window.location.origin}/books/${bookId}`,
      }),
    });

    if (!response.ok) {
      throw new Error('Failed to create checkout session');
    }

    const { url } = await response.json();

    if (!url) {
      throw new Error('No checkout URL returned');
    }

    // Redirect to Stripe Checkout using standard redirect
    window.location.href = url;
  }

  /**
   * Get price ID for a book (uses state file)
   */
  static getPriceId(productKey: string): string | undefined {
    return StripeState.getPriceId(productKey);
  }

  /**
   * Check if Stripe is configured
   */
  static isConfigured(): boolean {
    const publishableKey = import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY;
    const hasPrices = StripeState.isConfigured();
    return !!publishableKey && publishableKey !== 'your_publishable_key' && hasPrices;
  }

  /**
   * Load product prices from state file (call this on app init)
   */
  static async loadProducts(): Promise<void> {
    await StripeState.loadPrices();
  }
}
