/**
 * Stripe Product State Loader
 *
 * This file loads product/price IDs from the gitignored state file (.stripe-products.json)
 * that is generated by scripts/create-stripe-products.js
 *
 * The state file contains the actual price IDs for all 107 books × 2 payment options.
 */

interface PriceConfig {
  generatedAt: string;
  products: Array<{
    bookId: string;
    type: string;
    productId: string;
    priceId: string;
    productName: string;
  }>;
  priceIds: Record<string, string>;
}

// This will be populated from the state file
let priceIds: Record<string, string> = {};

/**
 * Load price IDs from state file
 *
 * Loads from stripe-products.test.json or stripe-products.production.json
 * based on VITE_STRIPE_MODE environment variable (defaults to 'test')
 */
export async function loadPrices(): Promise<Record<string, string>> {
  // If already loaded, return cached version
  if (Object.keys(priceIds).length > 0) {
    return priceIds;
  }

  // Determine which file to load based on environment
  const stripeMode = import.meta.env.VITE_STRIPE_MODE || 'test';
  const fileName = `/stripe-products.${stripeMode}.json`;

  try {
    // Try to load from mode-specific state file
    const response = await fetch(fileName);

    if (response.ok) {
      const config: PriceConfig = await response.json();
      priceIds = config.priceIds;
      console.log(`✅ Loaded ${Object.keys(priceIds).length} Stripe price IDs from ${fileName}`);
      return priceIds;
    } else {
      console.warn(`⚠️ Could not load ${fileName} (status: ${response.status})`);
    }
  } catch (error) {
    console.warn(`⚠️ Could not load ${fileName} - using fallback`);
  }

  // Fallback: return empty object (will show "not configured" error)
  console.warn(`⚠️ No Stripe products configured for mode "${stripeMode}". Run: npm run stripe:create`);
  return {};
}

/**
 * Get price ID synchronously (use after loadPrices has been called)
 */
export function getPriceId(productKey: string): string | undefined {
  return priceIds[productKey];
}

/**
 * Check if products are configured
 */
export function isConfigured(): boolean {
  return Object.keys(priceIds).length > 0;
}

/**
 * Get all price IDs (for debugging)
 */
export function getAllPriceIds(): Record<string, string> {
  return { ...priceIds };
}

// Auto-load on module import (in browser environment)
if (typeof window !== 'undefined') {
  loadPrices().catch((error) => {
    console.error('Failed to load Stripe products:', error);
  });
}

export default {
  loadPrices,
  getPriceId,
  isConfigured,
  getAllPriceIds,
};
